---

# useradd {{ username }}
# passwd {{ username }}
# su - {{ username }}
#
# ssh-keygen -t rsa

- hosts: all
  tasks:
    - name: create user
      user: name={{ username }} shell=/bin/bash createhome=yes

    - name: set authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        state: present

    - name: update sudoers file
      lineinfile:
        path: /etc/sudoers
        insertafter: EOF
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        regexp: '^{{ username }} .*'
        state: present
        validate: '/usr/sbin/visudo -cf %s'
