---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
binary_dir:    "{{ playbook_dir }}/resources/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

codis_dir: "{{ playbook_dir }}/resources"

coordinator_name: "etcd"

coordinator_addr: "10.0.0.140:12379,10.0.0.140:22379,10.0.0.140:32379"

codis_install_dir: /opt/codis

product_name: codis-cluster

product_auth: hellotalk

dashboard_addr: 127.0.0.1:18080

proxy_addr: 127.0.0.1:19000

proxy_admin_addr: 127.0.0.1:11080

codis_server_workdir: /data/redis-6379

codis_server_port: 6379

redis_sentinel_workdir: /data/sentinel-26379

redis_sentinel_port: 26379
