---

## Global variables

ansible_user: "root"

ansible_port: "22"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"

codis_dir: /Users/issenn/go/src/.com/CodisLabs/codis

coordinator_name: "etcd"

coordinator_addr: "127.0.0.1:12379,127.0.0.1:22379,127.0.0.1:32379"

codis_install_dir: /Users/issenn/test/codis-vip

product_name: codis-cluster1

product_auth: hellotalk

dashboard_addr: 127.0.0.1:18080

proxy_addr: 127.0.0.1:19000

proxy_admin_addr: 127.0.0.1:11080

codis_server_workdir: /Users/issenn/test/data/redis-6379

codis_server_port: 6379

redis_sentinel_workdir: /Users/issenn/test/data/sentinel-26379

redis_sentinel_port: 26379
