---

- name: Create codis install directory
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  become: true
  with_items:
    - "{{ codis_install_dir }}"
    - "{{ codis_install_dir }}/bin"
    - "{{ codis_install_dir }}/config"
    - "{{ codis_install_dir }}/admin"

# - name: Create codis bin directory
#   file: path={{ codis_install_dir }}/bin state=directory owner=codis group=codis

# - name: Create codis conf directory
#   file: path={{ codis_install_dir }}/config state=directory owner=codis group=codis

# - name: Create codis admin directory
#   file: path={{ codis_install_dir }}/admin state=directory owner=codis group=codis
